Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -9,6 +9,11 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
+      - name: Set Permissions for Private Key
+        run: |
+          echo "${{ secrets.private_key }}" > private_key
+          chmod 400 private_key
+
       - name: Verify SSH Keys
         run: |
           rsa_key_found=false
@@ -33,8 +38,13 @@ jobs:
             exit 1
           fi
 
-          # Extract the private key from secrets
-          echo -e "${{ secrets.private_key }}" > private_key
+          # Check if both the public and private keys are present
+          if [[ $rsa_key_found == true ]]; then
+            echo "RSA key pair (2048-bit) complete."
+          else
+            echo "RSA key pair (2048-bit) missing."
+            exit 1
+          fi
 
           # Generate the corresponding public key from the private key
           ssh-keygen -y -f private_key > generated_public_key.pub
